apiVersion: v1
kind: Service
metadata:
 name: test-appdeux-service
spec:
 type: NodePort
 selector:
   app: test-appdeux
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 3000
   targetPort: 3000
   nodePort: 32223
